name: Continuous Preview Release

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  PNPM_VERSION: '10.12.1'

concurrency:
  group: continuous-preview-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  preview-release:
    name: 'Release preview'
    if: github.event_name == 'pull_request' || github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    container:
      image: node:22.13.1-alpine
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pin & bootstrap pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: npx turbo run build

      - name: Publish packages
        run: pnpm dlx pkg-pr-new publish './packages/*' --packageManager=pnpm --no-template
